import {test} from 'node:test';import assert from 'node:assert/strict';import {getProducts,categories,emptyFilters,filterProducts,searchProducts,formatPrice,stockStatus,purchaseLabel,getRelatedProducts} from '../src/lib/catalogue';import {createWhatsAppUrl,createProductPurchaseMessage,createGeneralInquiryMessage} from '../src/lib/whatsapp';import fs from 'node:fs';
test('24 unique demo products cover all categories and use local assets',()=>{const all=getProducts();assert.equal(all.length,24);assert.equal(new Set(all.map(p=>p.slug)).size,24);for(const c of categories)assert.ok(all.some(p=>p.categoryId===c.id));for(const p of all){assert.ok(p.sampleData);assert.ok(fs.existsSync('public'+p.image));for(const image of p.gallery)assert.ok(fs.existsSync('public'+image));}});
test('multiword search matches brand and specs',()=>{const result=searchProducts('Haier inverter');assert.equal(result.length,2);assert.ok(result.every(p=>p.brand==='Haier'));assert.equal(searchProducts('imaginary-nonexistent-item').length,0);});
test('combined filters, availability, price and clear state',()=>{assert.equal(filterProducts({...emptyFilters,category:'air-conditioners',brand:'Haier'}).length,1);assert.equal(filterProducts({...emptyFilters,availability:'outOfStock'}).length,1);assert.equal(filterProducts({...emptyFilters,availability:'onOrder'}).length,1);assert.equal(filterProducts({...emptyFilters,availability:'lowStock'}).length,1);const priced=filterProducts({...emptyFilters,min:'10000',max:'50000'});assert.ok(priced.every(p=>p.showPrice&&p.price!>=10000&&p.price!<=50000));assert.equal(filterProducts(emptyFilters).length,24);assert.ok(filterProducts({...emptyFilters,featured:true}).every(p=>p.featured));assert.ok(filterProducts({...emptyFilters,newArrival:true}).every(p=>p.newArrival));});
test('price and alphabetical sorting',()=>{const low=filterProducts({...emptyFilters,sort:'price-asc'}).filter(p=>p.showPrice).map(p=>p.price!);assert.deepEqual(low,[...low].sort((a,b)=>a-b));const high=filterProducts({...emptyFilters,sort:'price-desc'}).filter(p=>p.showPrice).map(p=>p.price!);assert.deepEqual(high,[...high].sort((a,b)=>b-a));const names=filterProducts({...emptyFilters,sort:'name'}).map(p=>p.name);assert.deepEqual(names,[...names].sort((a,b)=>a.localeCompare(b)));});
test('hidden and zero prices are never displayed as free',()=>{assert.equal(formatPrice({price:0,showPrice:true,priceLabel:null}),'Contact for Latest Price');assert.equal(formatPrice({price:123,showPrice:false,priceLabel:'Secret'}),'Contact for Latest Price');});
test('stock precedence and related products',()=>{const p=getProducts().find(p=>p.outOfStock)!;assert.equal(stockStatus(p),'Out of stock');assert.equal(purchaseLabel(p),'Ask About Availability');assert.ok(getRelatedProducts(p).every(x=>x.id!==p.id));});
test('WhatsApp encoding preserves quantity, variants and actual URL',()=>{const p=getProducts()[0];const message=createProductPurchaseMessage(p,3,{'Screen size':'43 inch',Empty:''},'https://demo.example/products/'+p.slug);assert.ok(message.includes('Quantity: 3'));assert.ok(message.includes('Screen size: 43 inch'));assert.ok(!message.includes('Empty:'));assert.ok(message.includes('https://demo.example/products/'+p.slug));assert.ok(message.includes(p.name));const url=new URL(createWhatsAppUrl(message));assert.equal(url.hostname,'wa.me');assert.match(url.pathname,/^\/\d+$/);assert.equal(url.searchParams.get('text'),message);});
test('quick and general inquiries omit empty fields',()=>{assert.ok(createProductPurchaseMessage(getProducts()[0],1,{},undefined,true).includes('latest price and availability'));const message=createGeneralInquiryMessage({Name:'Ali',Phone:'',Message:'Price & availability?'});assert.ok(message.includes('Name: Ali'));assert.ok(!message.includes('Phone:'));assert.equal(new URL(createWhatsAppUrl(message)).searchParams.get('text'),message);});
